### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by ndsvw** [github-drama/github-drama#52]
Hello, I found some broken hyperlinks:

- [ ] https://github.com/CVarisco/community-story/pull/1 (file: README.md, status code: 404)
- [ ] https://boards.4channel.org/g/thread/91848262#p91850335 (file: README.md, status code: 404)
- [ ] https://boards.4channel.org/g/thread/91870752 (file: README.md, status code: 404)
- [ ] https://kiwifarms.net/threads/mypal-browser-is-dead.99665/ (file: README.md, error: EAI_AGAIN)
- [ ] https://kiwifarms.net/threads/palemoon-dev-tobin-ntp-new-tobin-paradigm-leaves-the-project.114903/ (file: README.md, error: EAI_AGAIN)
- [ ] https://boards.4channel.org/g/thread/83929918 (file: README.md, status code: 404)
- [ ] https://boards.4channel.org/g/thread/85518484 (file: README.md, status code: 404)
- [ ] https://boards.4channel.org/g/thread/86124256 (file: README.md, status code: 404)
- [ ] https://boards.4channel.org/g/thread/91238463 (file: README.md, status code: 404)
- [ ] https://kiwifarms.net/threads/coraline-ada-ehmke-corey-dale-ehmke.31003/ (file: README.md, error: EAI_AGAIN)
- [ ] https://boards.4channel.org/g/thread/48559828 (file: README.md, status code: 404)
- [ ] https://boards.4channel.org/g/thread/48569752 (file: README.md, status code: 404)
- [ ] https://boards.4channel.org/g/thread/48575151 (file: README.md, status code: 404)
- [ ] https://boards.4channel.org/g/thread/90214421 (file: README.md, status code: 404)
- [ ] https://github.com/opencart/opencart/issues/3834 (file: README.md, status code: 404)
- [ ] https://github.com/PiotrGrochowski/Consolas/issues/1 (file: README.md, status code: 404)
- [ ] https://github.com/RIAEvangelist/node-ipc/issues/233 (file: README.md, status code: 404)
- [ ] https://github.com/tenacityteam/tenacity/issues/99 (file: README.md, status code: 404)
- [ ] https://boards.4channel.org/g/thread/91675671 (file: README.md, status code: 404)
- [ ] https://kiwifarms.net/threads/open-source-software-community.38130/post-5930885 (file: README.md, error: EAI_AGAIN)
